#!/usr/bin/env bash
# Local QA of SP1 (smart-portal-1) + SP2 (smart-portal-2) TOGETHER, fully emulated.
#
#   One Firebase emulator session, demo project "demo-sp-qa":
#     - SP2 data  → Firestore database "(default)"   (as in production: its own database)
#     - SP1 data  → Firestore database "portal"
#     - Functions of BOTH systems, so the triggers and the SP1 ↔ SP2 syncs run for real.
#
#   Production is never touched:
#     1. "demo-" project: Google rejects any real call for it.
#     2. No Google credentials in this process (empty HOME, no ADC). Checked below:
#        if credentials can be loaded, the script STOPS.
#     3. The functions get a QA-only env with NO production keys (Resend, Workspace, sync
#        secrets, carriers). SP1 ↔ SP2 URLs point to this local emulator.
#     4. Scheduled functions do not run by themselves in the emulator.
#
#   Known limits (documented in docs/QA_EMULATOR_SP1_SP2.md):
#     - SP2's slMLockerProxy and slSendPasswordReset are not loaded (same name as SP1's).
#     - SP1 staff and SP2 customers share one Auth emulator (separate projects in production).
#     - functions/src/prealerts/sync.ts has ML Cargo / portal credentials in code: do not call
#       triggerPreAlertSync in QA (it would only READ tracking data from those providers).
#
# Usage:  scripts/qa-emulator/start.sh        (then seed.sh, web-sp1.sh, web-sp2.sh)
set -euo pipefail

SP1_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
SP2_DIR="${SP2_DIR:-$(cd "$SP1_DIR/../smart-portal-2" && pwd)}"
QA_DIR="${QA_DIR:-${TMPDIR:-/tmp}/sp-qa-emulator}"
PROJECT_ID="demo-sp-qa"
FN="http://127.0.0.1:5001/${PROJECT_ID}/us-central1"
BLOCKED_URL="http://127.0.0.1:9/emulator-blocked"   # port 9 = connection refused, instantly
OFF="emulator-disabled"
SYNC_SECRET="qa-local-sync-secret"                   # same value on both sides, local only

[ -f "$SP2_DIR/src/functions/package.json" ] || { echo "❌ SP2 not found at $SP2_DIR (set SP2_DIR)"; exit 1; }

# ── 1. Build both functions (TypeScript only, no version bump) ───────────────────────
(cd "$SP1_DIR/functions" && npx tsc)
(cd "$SP2_DIR/src/functions" && npx tsc)
echo "✅ SP1 and SP2 functions compiled"

# ── 2. No Google credentials in this process ─────────────────────────────────────────
# google-auth-library looks for credentials in $HOME/.config/gcloud (CLOUDSDK_CONFIG is NOT
# enough). The emulator runs with an empty HOME, so there is nothing to find. (A fake
# GOOGLE_APPLICATION_CREDENTIALS does not work: firebase-admin fails at initializeApp.)
REAL_HOME="$HOME"
export HOME="$QA_DIR/home"
mkdir -p "$HOME/.cache"
[ -e "$HOME/.cache/firebase" ] || ln -s "$REAL_HOME/.cache/firebase" "$HOME/.cache/firebase"   # emulator jars only
unset GOOGLE_APPLICATION_CREDENTIALS GOOGLE_CLOUD_PROJECT GCLOUD_PROJECT CLOUDSDK_CONFIG || true
if (cd "$SP1_DIR/functions" && node -e "
  const { GoogleAuth } = require('google-auth-library');
  new GoogleAuth({ scopes: ['https://www.googleapis.com/auth/cloud-platform'] }).getClient()
    .then(() => process.exit(0)).catch(() => process.exit(1));
" 2>/dev/null); then
  echo "❌ Google credentials are available to this process. Refusing to start (could reach production)."
  exit 1
fi
echo "✅ No Google credentials: nothing here can reach a real Google/Firebase project"

# ── 3. QA project folder (generated, outside both repos) ─────────────────────────────
rm -rf "$QA_DIR/sp1" "$QA_DIR/sp2" "$QA_DIR/rules"
mkdir -p "$QA_DIR/sp1" "$QA_DIR/sp2" "$QA_DIR/rules"
cp "$SP2_DIR/firestore.rules" "$QA_DIR/rules/sp2.rules"
cp "$SP1_DIR/firestore.rules" "$QA_DIR/rules/sp1.rules"

wrapper() {   # $1 = dir, $2 = real functions dir, $3 = names to skip (space separated)
  ln -s "$2/node_modules" "$1/node_modules"
  node -e "
    const real = require('$2/package.json');
    require('fs').writeFileSync('$1/package.json', JSON.stringify({
      name: 'qa-' + real.name, private: true, main: 'index.js',
      engines: { node: '22' }, dependencies: real.dependencies,
    }, null, 2));"
  cat > "$1/index.js" <<EOF
// GENERATED by scripts/qa-emulator/start.sh — loads the REAL compiled functions of
// $2 and exports them to the QA emulator (skipping: ${3:-none}).
const real = require('$2/lib/index.js');
const skip = new Set('${3}'.split(' ').filter(Boolean));
for (const [name, fn] of Object.entries(real)) if (!skip.has(name)) exports[name] = fn;
EOF
}
wrapper "$QA_DIR/sp2" "$SP2_DIR/src/functions" "slMLockerProxy slSendPasswordReset"
wrapper "$QA_DIR/sp1" "$SP1_DIR/functions" ""

# QA env for SP2 functions: no production keys; SP1 = this emulator.
cat > "$QA_DIR/sp2/.env" <<EOF
# GENERATED — QA only. No production keys. SP1 = local emulator.
SP1_CUSTOMER_SYNC_URL=${FN}/slSyncCustomerFromSp2
SP1_ENCOMIENDA_SYNC_URL=${FN}/slSyncEncomiendaFromSp2
SP1_LOOKUP_CUSTOMER_URL=${FN}/slLookupCustomerByEmail
SP1_DELETE_ACCOUNT_URL=${FN}/slDeleteAccountFromSp2
SP1_SET_PACKAGES_STATUS_URL=${FN}/slSetPackagesStatusFromSp2
SP1_API_URL=${BLOCKED_URL}
SP1_API_KEY=${OFF}
SP1_SECRET_KEY=${OFF}
ENCOMIENDA_SYNC_SECRET=${SYNC_SECRET}
MIDDLEWARE_API_URL=${BLOCKED_URL}
MIDDLEWARE_CACHE_INVALIDATE_URL=${BLOCKED_URL}
MLCARGO_BASE_URL=${BLOCKED_URL}
MLCARGO_USER=${OFF}
MLCARGO_PASSWORD=${OFF}
MLOCKER_PORTAL_USER=${OFF}
MLOCKER_PORTAL_PASS=${OFF}
MAYORISTA_PROVIDER_ENABLED=false
COLOMBIA_PROVIDER_ENABLED=false
COLOMBIA_PROVIDER_BASE_URL=${BLOCKED_URL}
CHINA_PROVIDER_BASE_URL=${BLOCKED_URL}
CHINA_PROVIDER_API_KEY=${OFF}
CHINA_PROVIDER_EMAIL=${OFF}
CHINA_PROVIDER_PASSWORD=${OFF}
CAINIAO_ENABLED=false
FEDEX_API_URL=${BLOCKED_URL}
FEDEX_CLIENT_ID=${OFF}
FEDEX_CLIENT_SECRET=${OFF}
USPS_USER_ID=
AFTERSHIP_API_KEY=${OFF}
TRACK17_API_KEY=${OFF}
TRACKINGMORE_API_KEY=${OFF}
SHIP24_API_KEY=${OFF}
PARCELSAPP_API_KEY=${OFF}
RESEND_API_KEY=${OFF}
RESEND_AUDIENCE_ID=${OFF}
RESEND_SEGMENT_ID=${OFF}
RESEND_SENDER_EMAIL=${OFF}
WORKSPACE_EMAIL=${OFF}
WORKSPACE_CLIENT_ID=${OFF}
WORKSPACE_CLIENT_SECRET=${OFF}
WORKSPACE_REFRESH_TOKEN=${OFF}
GOOGLE_WORKSPACE_AUTH_EMAIL=${OFF}
GOOGLE_WORKSPACE_SENDER_EMAIL=${OFF}
GOOGLE_WORKSPACE_CLIENT_ID=${OFF}
GOOGLE_WORKSPACE_CLIENT_SECRET=${OFF}
GOOGLE_WORKSPACE_REFRESH_TOKEN=${OFF}
SL_API_KEY=${OFF}
SL_CLIENT_ID=${OFF}
SL_SIGNATURE_SECRET=${OFF}
INVOICE_API_KEY=${OFF}
ORPHAN_CLEANUP_ENABLED=false
TRACKING_SEARCH_MODE=on
EOF

# QA env for SP1 functions: no production keys; SP2 = this emulator.
cat > "$QA_DIR/sp1/.env" <<EOF
# GENERATED — QA only. No production keys. SP2 = local emulator (same demo project).
SP2_PROJECT_ID=${PROJECT_ID}
SP2_SYNC_SECRET=${SYNC_SECRET}
ENCOMIENDA_SYNC_SECRET=${SYNC_SECRET}
SP2_SHIPMENT_SYNC_URL=${FN}/slSyncShipmentsFromSp1
SP2_CONSOLIDATION_SYNC_URL=${FN}/slSyncConsolidationFromSp1
SP2_INVOICE_SYNC_URL=${FN}/slSyncInvoicesFromSp1
SP2_DELETE_LOGIN_URL=${FN}/slDeleteLoginFromSp1
MLCARGO_USER=${OFF}
MLCARGO_PASSWORD=${OFF}
MLOCKER_PORTAL_USER=${OFF}
MLOCKER_PORTAL_PASS=${OFF}
RESEND_API_KEY=${OFF}
RESEND_AUDIENCE_ID=${OFF}
RESEND_SEGMENT_ID=${OFF}
RESEND_SENDER_EMAIL=${OFF}
RESEND_WEBHOOK_SECRET=${OFF}
WORKSPACE_EMAIL=${OFF}
WORKSPACE_CLIENT_ID=${OFF}
WORKSPACE_CLIENT_SECRET=${OFF}
WORKSPACE_REFRESH_TOKEN=${OFF}
GOOGLE_WORKSPACE_AUTH_EMAIL=${OFF}
GOOGLE_WORKSPACE_SENDER_EMAIL=${OFF}
GOOGLE_WORKSPACE_CLIENT_ID=${OFF}
GOOGLE_WORKSPACE_CLIENT_SECRET=${OFF}
GOOGLE_WORKSPACE_REFRESH_TOKEN=${OFF}
EOF

cat > "$QA_DIR/.firebaserc" <<EOF
{ "projects": { "default": "${PROJECT_ID}" } }
EOF
cat > "$QA_DIR/firebase.json" <<EOF
{
  "functions": [
    { "source": "sp2", "codebase": "sp2", "runtime": "nodejs22" },
    { "source": "sp1", "codebase": "sp1", "runtime": "nodejs22" }
  ],
  "firestore": [
    { "database": "(default)", "rules": "rules/sp2.rules" },
    { "database": "portal", "rules": "rules/sp1.rules" }
  ],
  "emulators": {
    "auth": { "port": 9099 },
    "firestore": { "port": 8080 },
    "functions": { "port": 5001 },
    "ui": { "enabled": true, "port": 4000 },
    "singleProjectMode": true
  }
}
EOF
echo "✅ QA project generated at $QA_DIR (no production keys)"

# ── 4. Start ─────────────────────────────────────────────────────────────────────────
export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"
cd "$QA_DIR"
exec firebase emulators:start --project "$PROJECT_ID"
