import {
  LayoutDashboard,
  Package,
  Map,
  Truck,
  Route,
  FileText,
  ClipboardList,
  CheckCircle,
  ScanLine,
  Warehouse,
  Building2,
  Users,
  UserCog,
  Palmtree,
  Sparkles,
  BarChart3,
  Settings,
  ScrollText,
} from "lucide-react";

export interface NavItem {
  label: string;
  href: string;
  icon: React.ReactNode;
  roles: string[];
  resource: string;
  section: string;
  subsection?: string;
  description?: string;
  keywords?: string[];
}

export const getNavigationItems = (t: (key: string) => string): NavItem[] => [
  // Operations
  {
    label: t("menu.dashboard"),
    href: "/dashboard",
    icon: <LayoutDashboard className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "STAFF", "AGENT", "DELIVERY", "CUSTOMER"],
    resource: "dashboard",
    section: "operations",
    keywords: ["panel", "inicio", "home", "dashboard"],
  },
  {
    label: t("menu.packages"),
    href: "/packages",
    icon: <Package className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "STAFF", "AGENT", "CUSTOMER"],
    resource: "packages",
    section: "operations",
    keywords: ["paquetes", "packages", "envios", "shipments"],
  },
  {
    label: t("menu.deliveries"),
    href: "/deliveries",
    icon: <Truck className="h-4 w-4" />,
    roles: ["DELIVERY", "AGENT", "ADMIN", "MANAGER"],
    resource: "deliveries",
    section: "operations",
    keywords: ["entregas", "deliveries", "envios", "distribucion", "repartos"],
  },
  {
    label: t("menu.routes"),
    href: "/routes",
    icon: <Map className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "routes",
    section: "operations",
    keywords: ["rutas", "routes", "caminos"],
  },
  {
    label: t("menu.invoices"),
    href: "/invoices",
    icon: <FileText className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "invoices",
    section: "operations",
    keywords: ["facturas", "invoices", "bills"],
  },
  {
    label: t("menu.quotes"),
    href: "/quotes",
    icon: <ClipboardList className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "AGENT"],
    resource: "quotes",
    section: "operations",
    keywords: ["cotizaciones", "quotes", "presupuesto", "estimate"],
  },
  {
    label: t("menu.manifests"),
    href: "/manifests",
    icon: <FileText className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "manifests",
    section: "operations",
    keywords: ["manifiestos", "manifests"],
  },
  // Tools
  {
    label: t("menu.tracking"),
    href: "/tracking",
    icon: <Map className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "STAFF", "AGENT", "CUSTOMER"],
    resource: "tracking",
    section: "tools",
    keywords: ["rastreo", "tracking", "seguimiento", "ubicacion", "mlcargo", "milocker"],
  },
  {
    label: t("menu.scanner"),
    href: "/scanner",
    icon: <ScanLine className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "STAFF", "AGENT", "DELIVERY", "CUSTOMER"],
    resource: "scanner",
    section: "tools",
    keywords: ["escaner", "scanner", "qr", "barcode", "camara"],
  },
  {
    label: t("menu.scannerBodega"),
    href: "/scanner/bodega",
    icon: <Warehouse className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "STAFF", "AGENT", "DELIVERY"],
    resource: "scanner",
    section: "tools",
    keywords: ["escaner", "bodega", "warehouse", "scanner", "barcode"],
  },
  {
    label: t("menu.scannerAdmin"),
    href: "/scanner/admin",
    icon: <ScanLine className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER", "STAFF"],
    resource: "scanner",
    section: "tools",
    keywords: ["escaner", "admin", "scanner", "asociar", "barcode"],
  },
  // Management
  {
    label: t("menu.customers"),
    href: "/customers",
    icon: <Users className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "customers",
    section: "management",
    keywords: ["clientes", "customers"],
  },
  {
    label: t("dashboard.statistics"),
    href: "/analytics",
    icon: <BarChart3 className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "analytics",
    section: "management",
    keywords: ["estadisticas", "statistics", "analytics", "analiticas"],
  },
  // HR/Payroll
  {
    label: t("menu.departments"),
    href: "/payroll/departments",
    icon: <Building2 className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "payroll",
    section: "hr",
    keywords: ["departamentos", "departments", "deptos"],
  },
  {
    label: t("menu.employees"),
    href: "/payroll/employees",
    icon: <Users className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "payroll",
    section: "hr",
    keywords: ["empleados", "employees", "personal", "staff"],
  },
  {
    label: t("menu.benefits"),
    href: "/payroll/planilla",
    icon: <Palmtree className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "payroll",
    section: "hr",
    keywords: ["planilla", "beneficios", "benefits", "vacaciones", "aguinaldo", "cesantia", "vacations", "christmas", "severance"],
  },
  {
    label: t("menu.runPayroll"),
    href: "/payroll/run",
    icon: <Sparkles className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "payroll",
    section: "hr",
    keywords: ["nomina", "payroll", "planilla", "salarios", "run", "ejecutar"],
  },
  // System
  {
    label: t("users.manage"),
    href: "/users",
    icon: <Users className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "users",
    section: "system",
    keywords: ["usuarios", "users", "gestion"],
  },
  {
    label: t("menu.settings"),
    href: "/settings",
    icon: <Settings className="h-4 w-4" />,
    roles: ["ADMIN", "CUSTOMER"],
    resource: "settings",
    section: "system",
    keywords: ["configuracion", "settings", "ajustes"],
  },
  {
    label: t("menu.encomiendas"),
    href: "/encomiendas",
    icon: <Truck className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "settings",
    section: "management",
    subsection: "mgmt-plataforma",
    description: t("menu.encomiendasDesc"),
    keywords: ["encomiendas", "courier", "envio", "paquetes", "empresa"],
  },
  {
    label: t("menu.encomiendaDispatch"),
    href: "/encomiendas/salida",
    icon: <ClipboardList className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "encomiendas",
    section: "management",
    subsection: "mgmt-plataforma",
    description: t("menu.encomiendaDispatchDesc"),
    keywords: ["encomiendas", "salida", "despacho", "ruta", "boleta", "dispatch"],
  },
  {
    label: t("menu.releaseNotes"),
    href: "/release",
    icon: <ScrollText className="h-4 w-4" />,
    roles: ["ADMIN", "MANAGER"],
    resource: "settings",
    section: "management",
    subsection: "mgmt-plataforma",
    description: t("menu.releaseNotesDesc"),
    keywords: ["changelog", "versiones", "updates", "release", "notas"],
  },
];
