"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditLogSchema = exports.SettingsSchema = exports.PermissionSchema = exports.QuoteSchema = exports.DeliverySchema = exports.RouteSchema = exports.InvoiceItemSchema = exports.InvoiceSchema = exports.InvoiceStatuses = exports.PackageSchema = exports.PackageStatuses = exports.CustomerSchema = exports.UserSchema = exports.UserRoles = void 0;
const zod_1 = require("zod");
exports.UserRoles = ["SUPER_ADMIN", "ADMIN", "AGENT", "DELIVERY", "VIEWER"];
exports.UserSchema = zod_1.z.object({
    id: zod_1.z.string(),
    email: zod_1.z.string().email(),
    fullName: zod_1.z.string().nullable().optional(),
    phone: zod_1.z.string().nullable().optional(),
    role: zod_1.z.enum(exports.UserRoles).default("AGENT"),
    status: zod_1.z.enum(["active", "inactive", "suspended"]).default("active"),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    lastLogin: zod_1.z.any().nullable().optional(),
});
exports.CustomerSchema = zod_1.z.object({
    id: zod_1.z.string(),
    fullName: zod_1.z.string(),
    firstName: zod_1.z.string().nullable().optional(),
    lastName: zod_1.z.string().nullable().optional(),
    dni: zod_1.z.string().nullable().optional(),
    email: zod_1.z.string().email(),
    phone: zod_1.z.string().nullable().optional(),
    address: zod_1.z.string().nullable().optional(),
    city: zod_1.z.string().nullable().optional(),
    country: zod_1.z.string().nullable().optional(),
    zipCode: zod_1.z.string().nullable().optional(),
    preferredRouteId: zod_1.z.string().nullable().optional(),
    status: zod_1.z.enum(["active", "inactive"]).default("active"),
    slCode: zod_1.z.string().nullable().optional(),
    tier: zod_1.z.string().default("basic"),
    membershipTier: zod_1.z.string().default("basic"),
    membershipExpires: zod_1.z.any().nullable().optional(),
    acceptMarketing: zod_1.z.boolean().default(false),
    consolidationEnabled: zod_1.z.boolean().default(false),
    deliveryAddress1: zod_1.z.string().nullable().optional(),
    deliveryAddress2: zod_1.z.string().nullable().optional(),
    deliveryAddress3: zod_1.z.string().nullable().optional(),
    notes: zod_1.z.string().nullable().optional(),
    memberSince: zod_1.z.any().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    createdBy: zod_1.z.string().nullable().optional(),
    updatedBy: zod_1.z.string().nullable().optional(),
});
exports.PackageStatuses = [
    "pending",
    "in_transit",
    "in_warehouse",
    "ready_for_delivery",
    "out_for_delivery",
    "delivered",
    "returned",
    "cancelled",
];
exports.PackageSchema = zod_1.z.object({
    id: zod_1.z.string(),
    trackingNumber: zod_1.z.string(),
    customerId: zod_1.z.string().nullable().optional(),
    customerName: zod_1.z.string(),
    status: zod_1.z.enum(exports.PackageStatuses).default("pending"),
    weight: zod_1.z.number(),
    origin: zod_1.z.string().nullable().optional(),
    destination: zod_1.z.string().nullable().optional(),
    routeId: zod_1.z.string().nullable().optional(),
    description: zod_1.z.string(),
    guideId: zod_1.z.string().nullable().optional(),
    consolidatedId: zod_1.z.string().nullable().optional(),
    isConsolidated: zod_1.z.boolean().default(false),
    calculatedCost: zod_1.z.number().nullable().optional(),
    costCalculationDate: zod_1.z.any().nullable().optional(),
    type: zod_1.z.enum(["air", "sea"]).default("air"),
    category: zod_1.z.string().nullable().optional(),
    branch: zod_1.z.string().nullable().optional(),
    flagStatus: zod_1.z.string().nullable().optional(),
    daysInSystem: zod_1.z.number().default(0),
    manifestNumber: zod_1.z.string().nullable().optional(),
    invoiceId: zod_1.z.string().nullable().optional(),
    invoiceReady: zod_1.z.boolean().default(false),
    invoicePdfUrl: zod_1.z.string().nullable().optional(),
    slCode: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    createdBy: zod_1.z.string().nullable().optional(),
});
exports.InvoiceStatuses = ["draft", "sent", "paid", "overdue", "cancelled"];
exports.InvoiceSchema = zod_1.z.object({
    id: zod_1.z.string(),
    customerId: zod_1.z.string(),
    invoiceNumber: zod_1.z.string(),
    status: zod_1.z.enum(exports.InvoiceStatuses).default("draft"),
    totalAmount: zod_1.z.number().default(0),
    subtotalAmount: zod_1.z.number().default(0),
    taxAmount: zod_1.z.number().nullable().optional(),
    taxRate: zod_1.z.number().default(0.13),
    discountAmount: zod_1.z.number().nullable().optional(),
    discountPercentage: zod_1.z.number().nullable().optional(),
    currency: zod_1.z.enum(["USD", "CRC"]).default("USD"),
    exchangeRate: zod_1.z.number().nullable().optional(),
    invoiceDate: zod_1.z.any(),
    dueDate: zod_1.z.any().nullable().optional(),
    sentAt: zod_1.z.any().nullable().optional(),
    paidAt: zod_1.z.any().nullable().optional(),
    notes: zod_1.z.string().nullable().optional(),
    internalNotes: zod_1.z.string().nullable().optional(),
    pdfUrl: zod_1.z.string().nullable().optional(),
    pdfPath: zod_1.z.string().nullable().optional(),
    clientSlCode: zod_1.z.string().nullable().optional(),
    clientEmail: zod_1.z.string().nullable().optional(),
    clientDni: zod_1.z.string().nullable().optional(),
    clientPhone: zod_1.z.string().nullable().optional(),
    paymentMethod: zod_1.z.string().nullable().optional(),
    paymentReference: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    createdBy: zod_1.z.string().nullable().optional(),
});
exports.InvoiceItemSchema = zod_1.z.object({
    id: zod_1.z.string(),
    invoiceId: zod_1.z.string(),
    packageId: zod_1.z.string().nullable().optional(),
    description: zod_1.z.string().nullable().optional(),
    quantity: zod_1.z.number().default(1),
    unitPrice: zod_1.z.number(),
    totalPrice: zod_1.z.number(),
    weight: zod_1.z.number().nullable().optional(),
    length: zod_1.z.number().nullable().optional(),
    width: zod_1.z.number().nullable().optional(),
    height: zod_1.z.number().nullable().optional(),
    origin: zod_1.z.string().nullable().optional(),
    destination: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.any(),
});
exports.RouteSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string(),
    description: zod_1.z.string().nullable().optional(),
    originLocation: zod_1.z.string(),
    destinationLocation: zod_1.z.string(),
    estimatedDistance: zod_1.z.number().nullable().optional(),
    estimatedDuration: zod_1.z.string().nullable().optional(),
    vehiclePlate: zod_1.z.string().nullable().optional(),
    vehicleType: zod_1.z.string().nullable().optional(),
    assignedAgentId: zod_1.z.string().nullable().optional(),
    status: zod_1.z.enum(["active", "inactive", "completed"]).default("active"),
    totalPackages: zod_1.z.number().default(0),
    completedPackages: zod_1.z.number().default(0),
    startTime: zod_1.z.any().nullable().optional(),
    endTime: zod_1.z.any().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    createdBy: zod_1.z.string().nullable().optional(),
});
exports.DeliverySchema = zod_1.z.object({
    id: zod_1.z.string(),
    trackingNumber: zod_1.z.string(),
    customerName: zod_1.z.string(),
    address: zod_1.z.string(),
    latitude: zod_1.z.number().nullable().optional(),
    longitude: zod_1.z.number().nullable().optional(),
    status: zod_1.z.enum(["pending", "in_progress", "completed", "failed"]).default("pending"),
    routeId: zod_1.z.string().nullable().optional(),
    assignedTo: zod_1.z.string().nullable().optional(),
    packageCount: zod_1.z.number().default(0),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    completedAt: zod_1.z.any().nullable().optional(),
});
exports.QuoteSchema = zod_1.z.object({
    id: zod_1.z.string(),
    customerId: zod_1.z.string(),
    quoteNumber: zod_1.z.string(),
    status: zod_1.z.enum(["draft", "sent", "accepted", "rejected", "expired", "converted"]).default("draft"),
    totalAmount: zod_1.z.number().default(0),
    subtotalAmount: zod_1.z.number().default(0),
    taxAmount: zod_1.z.number().nullable().optional(),
    validUntil: zod_1.z.any().nullable().optional(),
    notes: zod_1.z.string().nullable().optional(),
    convertedToInvoiceId: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
    createdBy: zod_1.z.string().nullable().optional(),
});
exports.PermissionSchema = zod_1.z.object({
    id: zod_1.z.string(),
    role: zod_1.z.string(),
    resource: zod_1.z.string(),
    action: zod_1.z.string(),
    allowed: zod_1.z.boolean().default(true),
    description: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
});
exports.SettingsSchema = zod_1.z.object({
    id: zod_1.z.string(),
    key: zod_1.z.string(),
    value: zod_1.z.string(),
    type: zod_1.z.enum(["string", "number", "boolean", "json"]).default("string"),
    category: zod_1.z.string().default("general"),
    description: zod_1.z.string().nullable().optional(),
    isPublic: zod_1.z.boolean().default(false),
    countryCode: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.any(),
    updatedAt: zod_1.z.any(),
});
exports.AuditLogSchema = zod_1.z.object({
    id: zod_1.z.string(),
    userId: zod_1.z.string().nullable().optional(),
    action: zod_1.z.string(),
    entity: zod_1.z.string(),
    entityId: zod_1.z.string(),
    oldValues: zod_1.z.record(zod_1.z.any()).nullable().optional(),
    newValues: zod_1.z.record(zod_1.z.any()).nullable().optional(),
    ipAddress: zod_1.z.string().nullable().optional(),
    userAgent: zod_1.z.string().nullable().optional(),
    status: zod_1.z.enum(["success", "failure"]).default("success"),
    errorMessage: zod_1.z.string().nullable().optional(),
    affectedRows: zod_1.z.number().nullable().optional(),
    createdAt: zod_1.z.any(),
});
//# sourceMappingURL=index.js.map