import { z } from "zod";
export declare const UserRoles: readonly ["SUPER_ADMIN", "ADMIN", "AGENT", "DELIVERY", "VIEWER"];
export type UserRole = (typeof UserRoles)[number];
export declare const UserSchema: z.ZodObject<{
    id: z.ZodString;
    email: z.ZodString;
    fullName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    phone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    role: z.ZodDefault<z.ZodEnum<["SUPER_ADMIN", "ADMIN", "AGENT", "DELIVERY", "VIEWER"]>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "suspended"]>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    lastLogin: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    email: string;
    role: "SUPER_ADMIN" | "ADMIN" | "AGENT" | "DELIVERY" | "VIEWER";
    status: "active" | "inactive" | "suspended";
    fullName?: string | null | undefined;
    phone?: string | null | undefined;
    createdAt?: any;
    updatedAt?: any;
    lastLogin?: any;
}, {
    id: string;
    email: string;
    fullName?: string | null | undefined;
    phone?: string | null | undefined;
    role?: "SUPER_ADMIN" | "ADMIN" | "AGENT" | "DELIVERY" | "VIEWER" | undefined;
    status?: "active" | "inactive" | "suspended" | undefined;
    createdAt?: any;
    updatedAt?: any;
    lastLogin?: any;
}>;
export type User = z.infer<typeof UserSchema>;
export declare const CustomerSchema: z.ZodObject<{
    id: z.ZodString;
    fullName: z.ZodString;
    firstName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    dni: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    email: z.ZodString;
    phone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    address: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    city: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    country: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    zipCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    preferredRouteId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive"]>>;
    slCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tier: z.ZodDefault<z.ZodString>;
    membershipTier: z.ZodDefault<z.ZodString>;
    membershipExpires: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    acceptMarketing: z.ZodDefault<z.ZodBoolean>;
    consolidationEnabled: z.ZodDefault<z.ZodBoolean>;
    deliveryAddress1: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    deliveryAddress2: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    deliveryAddress3: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    memberSince: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    createdBy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    updatedBy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    email: string;
    fullName: string;
    status: "active" | "inactive";
    tier: string;
    membershipTier: string;
    acceptMarketing: boolean;
    consolidationEnabled: boolean;
    phone?: string | null | undefined;
    createdAt?: any;
    updatedAt?: any;
    firstName?: string | null | undefined;
    lastName?: string | null | undefined;
    dni?: string | null | undefined;
    address?: string | null | undefined;
    city?: string | null | undefined;
    country?: string | null | undefined;
    zipCode?: string | null | undefined;
    preferredRouteId?: string | null | undefined;
    slCode?: string | null | undefined;
    membershipExpires?: any;
    deliveryAddress1?: string | null | undefined;
    deliveryAddress2?: string | null | undefined;
    deliveryAddress3?: string | null | undefined;
    notes?: string | null | undefined;
    memberSince?: any;
    createdBy?: string | null | undefined;
    updatedBy?: string | null | undefined;
}, {
    id: string;
    email: string;
    fullName: string;
    phone?: string | null | undefined;
    status?: "active" | "inactive" | undefined;
    createdAt?: any;
    updatedAt?: any;
    firstName?: string | null | undefined;
    lastName?: string | null | undefined;
    dni?: string | null | undefined;
    address?: string | null | undefined;
    city?: string | null | undefined;
    country?: string | null | undefined;
    zipCode?: string | null | undefined;
    preferredRouteId?: string | null | undefined;
    slCode?: string | null | undefined;
    tier?: string | undefined;
    membershipTier?: string | undefined;
    membershipExpires?: any;
    acceptMarketing?: boolean | undefined;
    consolidationEnabled?: boolean | undefined;
    deliveryAddress1?: string | null | undefined;
    deliveryAddress2?: string | null | undefined;
    deliveryAddress3?: string | null | undefined;
    notes?: string | null | undefined;
    memberSince?: any;
    createdBy?: string | null | undefined;
    updatedBy?: string | null | undefined;
}>;
export type Customer = z.infer<typeof CustomerSchema>;
export declare const PackageStatuses: readonly ["pending", "in_transit", "in_warehouse", "ready_for_delivery", "out_for_delivery", "delivered", "returned", "cancelled"];
export type PackageStatus = (typeof PackageStatuses)[number];
export declare const PackageSchema: z.ZodObject<{
    id: z.ZodString;
    trackingNumber: z.ZodString;
    customerId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    customerName: z.ZodString;
    status: z.ZodDefault<z.ZodEnum<["pending", "in_transit", "in_warehouse", "ready_for_delivery", "out_for_delivery", "delivered", "returned", "cancelled"]>>;
    weight: z.ZodNumber;
    origin: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    destination: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    routeId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    description: z.ZodString;
    guideId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    consolidatedId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isConsolidated: z.ZodDefault<z.ZodBoolean>;
    calculatedCost: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    costCalculationDate: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    type: z.ZodDefault<z.ZodEnum<["air", "sea"]>>;
    category: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    branch: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    flagStatus: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    daysInSystem: z.ZodDefault<z.ZodNumber>;
    manifestNumber: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    invoiceId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    invoiceReady: z.ZodDefault<z.ZodBoolean>;
    invoicePdfUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    slCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    createdBy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "pending" | "in_transit" | "in_warehouse" | "ready_for_delivery" | "out_for_delivery" | "delivered" | "returned" | "cancelled";
    type: "air" | "sea";
    trackingNumber: string;
    customerName: string;
    weight: number;
    description: string;
    isConsolidated: boolean;
    daysInSystem: number;
    invoiceReady: boolean;
    createdAt?: any;
    updatedAt?: any;
    slCode?: string | null | undefined;
    createdBy?: string | null | undefined;
    customerId?: string | null | undefined;
    origin?: string | null | undefined;
    destination?: string | null | undefined;
    routeId?: string | null | undefined;
    guideId?: string | null | undefined;
    consolidatedId?: string | null | undefined;
    calculatedCost?: number | null | undefined;
    costCalculationDate?: any;
    category?: string | null | undefined;
    branch?: string | null | undefined;
    flagStatus?: string | null | undefined;
    manifestNumber?: string | null | undefined;
    invoiceId?: string | null | undefined;
    invoicePdfUrl?: string | null | undefined;
}, {
    id: string;
    trackingNumber: string;
    customerName: string;
    weight: number;
    description: string;
    status?: "pending" | "in_transit" | "in_warehouse" | "ready_for_delivery" | "out_for_delivery" | "delivered" | "returned" | "cancelled" | undefined;
    createdAt?: any;
    updatedAt?: any;
    type?: "air" | "sea" | undefined;
    slCode?: string | null | undefined;
    createdBy?: string | null | undefined;
    customerId?: string | null | undefined;
    origin?: string | null | undefined;
    destination?: string | null | undefined;
    routeId?: string | null | undefined;
    guideId?: string | null | undefined;
    consolidatedId?: string | null | undefined;
    isConsolidated?: boolean | undefined;
    calculatedCost?: number | null | undefined;
    costCalculationDate?: any;
    category?: string | null | undefined;
    branch?: string | null | undefined;
    flagStatus?: string | null | undefined;
    daysInSystem?: number | undefined;
    manifestNumber?: string | null | undefined;
    invoiceId?: string | null | undefined;
    invoiceReady?: boolean | undefined;
    invoicePdfUrl?: string | null | undefined;
}>;
export type Package = z.infer<typeof PackageSchema>;
export declare const InvoiceStatuses: readonly ["draft", "sent", "paid", "overdue", "cancelled"];
export type InvoiceStatus = (typeof InvoiceStatuses)[number];
export declare const InvoiceSchema: z.ZodObject<{
    id: z.ZodString;
    customerId: z.ZodString;
    invoiceNumber: z.ZodString;
    status: z.ZodDefault<z.ZodEnum<["draft", "sent", "paid", "overdue", "cancelled"]>>;
    totalAmount: z.ZodDefault<z.ZodNumber>;
    subtotalAmount: z.ZodDefault<z.ZodNumber>;
    taxAmount: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    taxRate: z.ZodDefault<z.ZodNumber>;
    discountAmount: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    discountPercentage: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    currency: z.ZodDefault<z.ZodEnum<["USD", "CRC"]>>;
    exchangeRate: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    invoiceDate: z.ZodAny;
    dueDate: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    sentAt: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    paidAt: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    internalNotes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    pdfUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    pdfPath: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    clientSlCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    clientEmail: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    clientDni: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    clientPhone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    paymentMethod: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    paymentReference: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    createdBy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "cancelled" | "draft" | "sent" | "paid" | "overdue";
    customerId: string;
    invoiceNumber: string;
    totalAmount: number;
    subtotalAmount: number;
    taxRate: number;
    currency: "USD" | "CRC";
    createdAt?: any;
    updatedAt?: any;
    notes?: string | null | undefined;
    createdBy?: string | null | undefined;
    taxAmount?: number | null | undefined;
    discountAmount?: number | null | undefined;
    discountPercentage?: number | null | undefined;
    exchangeRate?: number | null | undefined;
    invoiceDate?: any;
    dueDate?: any;
    sentAt?: any;
    paidAt?: any;
    internalNotes?: string | null | undefined;
    pdfUrl?: string | null | undefined;
    pdfPath?: string | null | undefined;
    clientSlCode?: string | null | undefined;
    clientEmail?: string | null | undefined;
    clientDni?: string | null | undefined;
    clientPhone?: string | null | undefined;
    paymentMethod?: string | null | undefined;
    paymentReference?: string | null | undefined;
}, {
    id: string;
    customerId: string;
    invoiceNumber: string;
    status?: "cancelled" | "draft" | "sent" | "paid" | "overdue" | undefined;
    createdAt?: any;
    updatedAt?: any;
    notes?: string | null | undefined;
    createdBy?: string | null | undefined;
    totalAmount?: number | undefined;
    subtotalAmount?: number | undefined;
    taxAmount?: number | null | undefined;
    taxRate?: number | undefined;
    discountAmount?: number | null | undefined;
    discountPercentage?: number | null | undefined;
    currency?: "USD" | "CRC" | undefined;
    exchangeRate?: number | null | undefined;
    invoiceDate?: any;
    dueDate?: any;
    sentAt?: any;
    paidAt?: any;
    internalNotes?: string | null | undefined;
    pdfUrl?: string | null | undefined;
    pdfPath?: string | null | undefined;
    clientSlCode?: string | null | undefined;
    clientEmail?: string | null | undefined;
    clientDni?: string | null | undefined;
    clientPhone?: string | null | undefined;
    paymentMethod?: string | null | undefined;
    paymentReference?: string | null | undefined;
}>;
export type Invoice = z.infer<typeof InvoiceSchema>;
export declare const InvoiceItemSchema: z.ZodObject<{
    id: z.ZodString;
    invoiceId: z.ZodString;
    packageId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    quantity: z.ZodDefault<z.ZodNumber>;
    unitPrice: z.ZodNumber;
    totalPrice: z.ZodNumber;
    weight: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    length: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    width: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    height: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    origin: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    destination: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodAny;
}, "strip", z.ZodTypeAny, {
    id: string;
    invoiceId: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
    createdAt?: any;
    length?: number | null | undefined;
    weight?: number | null | undefined;
    origin?: string | null | undefined;
    destination?: string | null | undefined;
    description?: string | null | undefined;
    packageId?: string | null | undefined;
    width?: number | null | undefined;
    height?: number | null | undefined;
}, {
    id: string;
    invoiceId: string;
    unitPrice: number;
    totalPrice: number;
    createdAt?: any;
    length?: number | null | undefined;
    weight?: number | null | undefined;
    origin?: string | null | undefined;
    destination?: string | null | undefined;
    description?: string | null | undefined;
    packageId?: string | null | undefined;
    quantity?: number | undefined;
    width?: number | null | undefined;
    height?: number | null | undefined;
}>;
export type InvoiceItem = z.infer<typeof InvoiceItemSchema>;
export declare const RouteSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    originLocation: z.ZodString;
    destinationLocation: z.ZodString;
    estimatedDistance: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    estimatedDuration: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    vehiclePlate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    vehicleType: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    assignedAgentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "completed"]>>;
    totalPackages: z.ZodDefault<z.ZodNumber>;
    completedPackages: z.ZodDefault<z.ZodNumber>;
    startTime: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    endTime: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    createdBy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "active" | "inactive" | "completed";
    name: string;
    originLocation: string;
    destinationLocation: string;
    totalPackages: number;
    completedPackages: number;
    createdAt?: any;
    updatedAt?: any;
    createdBy?: string | null | undefined;
    description?: string | null | undefined;
    estimatedDistance?: number | null | undefined;
    estimatedDuration?: string | null | undefined;
    vehiclePlate?: string | null | undefined;
    vehicleType?: string | null | undefined;
    assignedAgentId?: string | null | undefined;
    startTime?: any;
    endTime?: any;
}, {
    id: string;
    name: string;
    originLocation: string;
    destinationLocation: string;
    status?: "active" | "inactive" | "completed" | undefined;
    createdAt?: any;
    updatedAt?: any;
    createdBy?: string | null | undefined;
    description?: string | null | undefined;
    estimatedDistance?: number | null | undefined;
    estimatedDuration?: string | null | undefined;
    vehiclePlate?: string | null | undefined;
    vehicleType?: string | null | undefined;
    assignedAgentId?: string | null | undefined;
    totalPackages?: number | undefined;
    completedPackages?: number | undefined;
    startTime?: any;
    endTime?: any;
}>;
export type Route = z.infer<typeof RouteSchema>;
export declare const DeliverySchema: z.ZodObject<{
    id: z.ZodString;
    trackingNumber: z.ZodString;
    customerName: z.ZodString;
    address: z.ZodString;
    latitude: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    longitude: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    status: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "failed"]>>;
    routeId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    assignedTo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    packageCount: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    completedAt: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "pending" | "completed" | "in_progress" | "failed";
    address: string;
    trackingNumber: string;
    customerName: string;
    packageCount: number;
    createdAt?: any;
    updatedAt?: any;
    routeId?: string | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    assignedTo?: string | null | undefined;
    completedAt?: any;
}, {
    id: string;
    address: string;
    trackingNumber: string;
    customerName: string;
    status?: "pending" | "completed" | "in_progress" | "failed" | undefined;
    createdAt?: any;
    updatedAt?: any;
    routeId?: string | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    assignedTo?: string | null | undefined;
    packageCount?: number | undefined;
    completedAt?: any;
}>;
export type Delivery = z.infer<typeof DeliverySchema>;
export declare const QuoteSchema: z.ZodObject<{
    id: z.ZodString;
    customerId: z.ZodString;
    quoteNumber: z.ZodString;
    status: z.ZodDefault<z.ZodEnum<["draft", "sent", "accepted", "rejected", "expired", "converted"]>>;
    totalAmount: z.ZodDefault<z.ZodNumber>;
    subtotalAmount: z.ZodDefault<z.ZodNumber>;
    taxAmount: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    validUntil: z.ZodOptional<z.ZodNullable<z.ZodAny>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    convertedToInvoiceId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
    createdBy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "draft" | "sent" | "accepted" | "rejected" | "expired" | "converted";
    customerId: string;
    totalAmount: number;
    subtotalAmount: number;
    quoteNumber: string;
    createdAt?: any;
    updatedAt?: any;
    notes?: string | null | undefined;
    createdBy?: string | null | undefined;
    taxAmount?: number | null | undefined;
    validUntil?: any;
    convertedToInvoiceId?: string | null | undefined;
}, {
    id: string;
    customerId: string;
    quoteNumber: string;
    status?: "draft" | "sent" | "accepted" | "rejected" | "expired" | "converted" | undefined;
    createdAt?: any;
    updatedAt?: any;
    notes?: string | null | undefined;
    createdBy?: string | null | undefined;
    totalAmount?: number | undefined;
    subtotalAmount?: number | undefined;
    taxAmount?: number | null | undefined;
    validUntil?: any;
    convertedToInvoiceId?: string | null | undefined;
}>;
export type Quote = z.infer<typeof QuoteSchema>;
export declare const PermissionSchema: z.ZodObject<{
    id: z.ZodString;
    role: z.ZodString;
    resource: z.ZodString;
    action: z.ZodString;
    allowed: z.ZodDefault<z.ZodBoolean>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
}, "strip", z.ZodTypeAny, {
    id: string;
    role: string;
    resource: string;
    action: string;
    allowed: boolean;
    createdAt?: any;
    updatedAt?: any;
    description?: string | null | undefined;
}, {
    id: string;
    role: string;
    resource: string;
    action: string;
    createdAt?: any;
    updatedAt?: any;
    description?: string | null | undefined;
    allowed?: boolean | undefined;
}>;
export type Permission = z.infer<typeof PermissionSchema>;
export declare const SettingsSchema: z.ZodObject<{
    id: z.ZodString;
    key: z.ZodString;
    value: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["string", "number", "boolean", "json"]>>;
    category: z.ZodDefault<z.ZodString>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isPublic: z.ZodDefault<z.ZodBoolean>;
    countryCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodAny;
    updatedAt: z.ZodAny;
}, "strip", z.ZodTypeAny, {
    id: string;
    value: string;
    type: "string" | "number" | "boolean" | "json";
    category: string;
    key: string;
    isPublic: boolean;
    createdAt?: any;
    updatedAt?: any;
    description?: string | null | undefined;
    countryCode?: string | null | undefined;
}, {
    id: string;
    value: string;
    key: string;
    createdAt?: any;
    updatedAt?: any;
    type?: "string" | "number" | "boolean" | "json" | undefined;
    description?: string | null | undefined;
    category?: string | undefined;
    isPublic?: boolean | undefined;
    countryCode?: string | null | undefined;
}>;
export type Settings = z.infer<typeof SettingsSchema>;
export declare const AuditLogSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    action: z.ZodString;
    entity: z.ZodString;
    entityId: z.ZodString;
    oldValues: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodAny>>>;
    newValues: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodAny>>>;
    ipAddress: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    userAgent: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["success", "failure"]>>;
    errorMessage: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    affectedRows: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    createdAt: z.ZodAny;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "success" | "failure";
    action: string;
    entity: string;
    entityId: string;
    createdAt?: any;
    userId?: string | null | undefined;
    oldValues?: Record<string, any> | null | undefined;
    newValues?: Record<string, any> | null | undefined;
    ipAddress?: string | null | undefined;
    userAgent?: string | null | undefined;
    errorMessage?: string | null | undefined;
    affectedRows?: number | null | undefined;
}, {
    id: string;
    action: string;
    entity: string;
    entityId: string;
    status?: "success" | "failure" | undefined;
    createdAt?: any;
    userId?: string | null | undefined;
    oldValues?: Record<string, any> | null | undefined;
    newValues?: Record<string, any> | null | undefined;
    ipAddress?: string | null | undefined;
    userAgent?: string | null | undefined;
    errorMessage?: string | null | undefined;
    affectedRows?: number | null | undefined;
}>;
export type AuditLog = z.infer<typeof AuditLogSchema>;
export interface ApiResponse<T = unknown> {
    success: boolean;
    data?: T;
    error?: string;
    message?: string;
}
export interface PaginatedResponse<T> extends ApiResponse<T[]> {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
}
export interface AuthenticatedRequest {
    uid: string;
    email?: string;
    role?: UserRole;
}
//# sourceMappingURL=index.d.ts.map