/**
 * Nova — the invoice pill in a customer group row (2026-09-26, requested by the user): instead of the fixed
 * "Factura única" / "Factura consolidada", show WHICH invoice and its STATE, e.g. "…234230-C [Borrador]",
 * so the admin sees at a glance whether the invoice is still a draft or already sent / paid (a sent invoice
 * is only regenerated by the admin's explicit action). Pure; tested in __tests__/invoice-badge.spec.ts.
 */
const STATUS: Record<string, { label: string; tone: string }> = {
  draft:           { label: 'Borrador',  tone: 'bg-slate-500/15 text-slate-700 dark:text-slate-300 border-slate-500/30' },
  sent:            { label: 'Enviada',   tone: 'bg-blue-500/15 text-blue-700 dark:text-blue-300 border-blue-500/30' },
  paid:            { label: 'Pagada',    tone: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-500/30' },
  pending:         { label: 'Pendiente', tone: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30' },
  pending_payment: { label: 'Pendiente', tone: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30' },
  overdue:         { label: 'Vencida',   tone: 'bg-orange-500/15 text-orange-700 dark:text-orange-300 border-orange-500/30' },
  annulled:        { label: 'Anulada',   tone: 'bg-red-500/15 text-red-700 dark:text-red-300 border-red-500/30' },
  cancelled:       { label: 'Anulada',   tone: 'bg-red-500/15 text-red-700 dark:text-red-300 border-red-500/30' },
};

/** "SL261404-20260925162655257" → "…655257"; "…-C" invoices keep their suffix: "…234230-C". */
export function shortInvoiceNumber(invoiceNumber: string | null | undefined): string {
  const n = String(invoiceNumber || '').trim();
  if (!n) return '—';
  const consolidated = /-C$/i.test(n);
  const core = consolidated ? n.slice(0, -2) : n;
  return `…${core.slice(-6)}${consolidated ? '-C' : ''}`;
}

export function invoiceBadge(invoiceNumber: string | null | undefined, status: string | null | undefined): { text: string; status: string; tone: string } {
  const s = STATUS[String(status || 'draft').toLowerCase()] ?? { label: String(status || 'Borrador'), tone: STATUS.draft.tone };
  return { text: `${shortInvoiceNumber(invoiceNumber)} [${s.label}]`, status: s.label, tone: s.tone };
}
